version: '3.7'

services:
  web:
    build: .
    container_name: test_fast_api
    command: uvicorn app:my_app --port ${FAST_API_PORT} --host 0.0.0.0 --reload
    restart: always
    env_file: .env
    ports:
      - "5000:${FAST_API_PORT}"
#    volumes:
#      - ./app:/app/
#      - staticfiles:/app/static/
#    expose:
#      - 8000
#    env_file:
#      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


#  db:
#    image: fastapi-sqlalchemy-asyncpg_db
#    build:
#      context: ./db
#      dockerfile: Dockerfile
#    volumes:
#      - fastapi_postgres_data:/var/lib/postgresql/data
#    env_file:
#      - .env
#      - .secrets
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=${SQL_USER}


volumes:
  postgres_data:
  staticfiles:
